import{S as y}from"./assets/vendor-CWwQENHe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const h="46065548-5ae4334dfe4b7f7d37f4bc842",g="https://pixabay.com/api/";async function f(r,t=1,n=12){const a=`${g}?key=${h}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${t}`;try{const e=await fetch(a);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error("Error fetching images:",e),e}}const d=document.querySelector(".gallery");function m(r){const t=r.map(n=>b(n)).join("");d.insertAdjacentHTML("beforeend",t),w()}function b({webformatURL:r,largeImageURL:t,tags:n,likes:a,views:e,comments:o,downloads:i}){return`
    <a href="${t}" class="gallery__item">
      <img src="${r}" alt="${n}" loading="lazy" class="gallery__image" />
      <div class="info">
        <p><b>Likes:</b> ${a}</p>
        <p><b>Views:</b> ${e}</p>
        <p><b>Comments:</b> ${o}</p>
        <p><b>Downloads:</b> ${i}</p>
      </div>
    </a>
  `}function L(){d.innerHTML=""}function s(r){iziToast.error({title:"Error",message:r})}let u;function w(){u?u.refresh():u=new y(".gallery a")}const $=document.querySelector("#search-form"),E=document.querySelector('input[name="searchQuery"]'),p=document.querySelector(".load-more");let l=1,c="";$.addEventListener("submit",S);p.addEventListener("click",P);async function S(r){if(r.preventDefault(),c=E.value.trim(),!c){s("Please enter a search query.");return}L(),l=1;try{const t=await f(c,l);if(t.hits.length===0){s("Sorry, there are no images matching your search query. Please try again!");return}m(t.hits),p.style.display="block"}catch{s("Failed to fetch images. Please try again later.")}}async function P(){l+=1;try{const r=await f(c,l);m(r.hits)}catch{s("Failed to fetch more images.")}}
//# sourceMappingURL=index.js.map
