import{i as h,S as p}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const y="46065548-5ae4334dfe4b7f7d37f4bc842",g="https://pixabay.com/api/";function b(o,r=1,n=12){const i=`${g}?key=${y}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${n}&page=${r}`;return fetch(i).then(e=>{if(!e.ok)throw new Error("Failed to fetch images");return e.json()}).catch(e=>{throw console.error("Error fetching images:",e),e})}const d=document.querySelector(".gallery");function L(o){const r=o.map(n=>$(n)).join("");d.insertAdjacentHTML("beforeend",r),w()}function $({webformatURL:o,largeImageURL:r,tags:n,likes:i,views:e,comments:t,downloads:a}){return`
    <a href="${r}" class="gallery__item">
      <img src="${o}" alt="${n}" loading="lazy" class="gallery__image" />
      <div class="info">
        <p><b>Likes:</b> ${i}</p>
        <p><b>Views:</b> ${e}</p>
        <p><b>Comments:</b> ${t}</p>
        <p><b>Downloads:</b> ${a}</p>
      </div>
    </a>
  `}function S(){d.innerHTML=""}function s(o){h.error({title:"Error",message:o})}let c;function w(){c?c.refresh():c=new p(".gallery a")}const E=document.querySelector("#search-form"),P=document.querySelector('input[name="searchQuery"]'),m=document.querySelector("#loader");let u=1,l="";E.addEventListener("submit",q);function q(o){if(o.preventDefault(),l=P.value.trim(),!l){s("Please enter a search query.");return}S(),_(),u=1,b(l,u).then(r=>{if(f(),r.hits.length===0){s("Sorry, there are no images matching your search query. Please try again!");return}L(r.hits)}).catch(r=>{f(),s("Failed to fetch images. Please try again later.")})}function _(){m.style.display="block"}function f(){m.style.display="none"}
//# sourceMappingURL=index.js.map
